### ISSUE TITLE
Max Revisions

### ISSUE THREAD

**Issue by brandonparsons** [ember-cli-deploy/ember-cli-deploy-lightning-pack#11]
Hi there, more of a question than an issue.

By default, does this plugin pack automatically keep a maximum number of revisions in Redis? Or is that something that needs to be set up separately?

**Comment by lukemelia** [comment]
@brandonparsons currently this is hardcoded to 10 in the redis plugin: https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/lib/redis.js#L32 We would accept a PR to make it configurable.

**Comment by brandonparsons** [comment]
Thanks for the quick follow-up @lukemelia ! Great work on this :)
