### ISSUE TITLE
ember-cli-deploy-rack

### ISSUE THREAD

**Issue by mkempe** [ember-cli-deploy/ember-cli-deploy-lightning-pack#17]
Hey there,

first of all, many thanks for creating Ember CLI Deploy and the ecosystem around - it's awesome.

For a new project, i created https://github.com/bitaculous/ember-cli-deploy-rack, a small Sinatra app, which connects to Redis and returns the uploaded index.html from `ember-cli-deploy-redis` including passing an revision parameter.

What do you think about it? If you like it, i am happy to move the repository under the `ember-cli-deploy` organization and would take care of it.

PS:  Sorry, if it is the wrong place to submit the request.

Thanks again.

**Comment by ghedamat** [comment]
hi @mkempe glad that you're liking the project!

I just had a quick look but your project seems great!

I think that as a starting point we could add a section about your project in the Docs for the ember-cli-deploy website that links to https://github.com/bitaculous/ember-cli-deploy-rack.

Maybe on this page: http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/lightning-strategy-examples/

let us know what you think!

**Comment by mkempe** [comment]
Hey @ghedamat,

thanks for your feedback!

That is a great idea, i opened a pull request: https://github.com/ember-cli/ember-cli-deploy/pull/345

**Comment by ghedamat** [comment]
perfect! thanks!
