### ISSUE TITLE
Using another ephemeral storage

### ISSUE THREAD

**Issue by bcardarella** [ember-cli-deploy/ember-cli-deploy-lightning-pack#19]
How tied to the implementation is Redis? Doing a quick code review it seems to be an expected dependency. I'm asking because in Elixir/Erlang we can rely on dets or ets instead of Redis to get the same result, the advantage being that dets and ets are built in, instead of having to rely on an external dependency.

**Comment by lukemelia** [comment]
The lightning pack consists of several plugins. All of the redis functionality is encapsulated within the redis plugin. If you swap that plugin out with an equivalent one that uses Elixir/Erlang functionality, it should work well. Note that our use of Redis in this case is not intended to be ephemeral but to have durability as it is the store for your index.html contents and deployment history.

**Comment by bcardarella** [comment]
> Note that our use of Redis in this case is not intended to be ephemeral but to have durability as it is the store for your index.html contents and deployment history

I see. I'll explore on what the best option is for Phoenix. Typically we see Redis being dropped in favor of an OTP library, but clearly it would have to be an interface that ember-cli can access

**Comment by lukemelia** [comment]
@bcardarella You could provide access via an API. https://github.com/tedconf/ember-cli-deploy-front-end-builds does this for Rails apps running the front-end-builds engine.

**Comment by bcardarella** [comment]
Confirm, thanks for the pointers. I'll close this out.
