### ISSUE TITLE
install hangs and will not continue

### ISSUE THREAD

**Issue by johnclittle** [ember-cli-deploy/ember-cli-deploy-lightning-pack#31]
After what I believe to be a fresh install of node and ember-cli I create a project and add both ember-cli-deploy and ember-cli-deploy-lightning-pack. On the ember-cli-deploy-lightning-pack the installation hangs. Here are a few of my key steps below. Any ideas?

$ember -v
ember-cli: 2.10.0
node: 6.9.1
os: darwin x64

ember new ember-quickstart
cd ember-quickstart

$ember install ember-cli-deploy
-works fine
$ember install ember-cli-deploy-lightning-pack
-Hangs here:
Installed packages for tooling via npm.
installing lightning-deploy-config
⸨                 ░⸩ ⠇ runTopLevelLifecycles: sill install printInstalled

**Comment by lukemelia** [comment]
Working OK here (see output below). Try `npm cache clean` perhaps?

```
➜  p ember new ecd-test
installing app
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/resolver.js
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.js
  create tests/.jshintrc
  create tests/helpers/destroy-app.js
  create tests/helpers/module-for-acceptance.js
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/integration/.gitkeep
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Successfully initialized git.
⠏ Installing packages for tooling via npm
Installed packages for tooling via npm.
Installed browser packages via Bower.
➜  p cd ecd-test
➜  ecd-test git:(master) ember install ember-cli-deploy
Installed packages for tooling via npm.
installing ember-cli-deploy
  create config/deploy.js
ember-cli-deploy needs plugins to actually do the deployment work.
See http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.5.x/quick-start/
to learn how to install plugins and see what plugins are available.
Installed addon package.
➜  ecd-test git:(master) ✗ ember install ember-cli-deploy-lightning-pack
Installed packages for tooling via npm.
installing lightning-deploy-config
? Overwrite config/deploy.js? Yes, overwrite
  overwrite config/deploy.js
Installed addon package.
➜  ecd-test git:(master) ✗
```

**Comment by johnclittle** [comment]
Luke, thanks for checking your side. I found that my terminal display on the my mac was not displaying the overwrite config/deploy.js prompt on a separate line and was therefore hidden from view behind the progress bar from the preceding command. This gave the appearance that the process was stalled. I am assuming this is a terminal display/configuration issue on my side. After recognizing this issue it is clear all is well.

Thank you and all the other maintainers for making this code available and for your support to the community.
