### ISSUE TITLE
then-redis yarn warning

### ISSUE THREAD

**Issue by maprules1000** [ember-cli-deploy/ember-cli-deploy-lightning-pack#36]
When using yarn to manage packages it throws the following warning:
`warning "then-redis@2.0.1" has unmet peer dependency "redis-commands@*".`

and the `then-redis` maintainer has [announced](https://github.com/mjackson/then-redis) he is no longer maintaining `then-redis` and that users should switch to [`node_redis`](https://github.com/NodeRedis/node_redis) which now contains promise goodness.

So, possible to drop `then-redis` and replace it with `node_redis`?

**Comment by lukemelia** [comment]
@maprules1000 good research and good recommendation! This should be opened on https://github.com/ember-cli-deploy/ember-cli-deploy-redis/issues. Do you mind opening there?
