### ISSUE TITLE
How to disable ember-cli-deploy-manifest

### ISSUE THREAD

**Issue by ccarterc** [ember-cli-deploy/ember-cli-deploy-lightning-pack#45]
It would be nice if it were possible to exclude certain files from the `manifest.txt` or be able to disable it entirely.

**Comment by achambers** [comment]
@ccarterc Read the “Disabling plugins” section of the configuration docs here http://ember-cli-deploy.com/docs/v1.0.x/configuration/ for info on how to disable a plugin. 

In terms of excluding files, you can do that via this config property https://github.com/ember-cli-deploy/ember-cli-deploy-manifest/blob/master/README.md#fileignorepattern

This issue really isn’t relevant to this repo either so I’m going to close it now. You can ask questions in the #ec-deploy channel as I mentioned in your previous issue.
