### ISSUE TITLE
deploy.js generator doesn't run properly

### ISSUE THREAD

**Issue by raycohen** [ember-cli-deploy/ember-cli-deploy-lightning-pack#6]
running ember install yields an "identical" deploy.js to the one that ember-cli-deploy brings
```
$ ember install ember-cli-deploy@0.5.0-beta.2
  create config/deploy.js

$ ember install ember-cli-deploy-lightning-pack@beta
  identical config/deploy.js
```

I had to run `ember g lightning-deploy-config` manually to get the deploy.js file provided by this project's blueprints

**Comment by achambers** [comment]
Thanks @raycohen. Will take a look at it. As always, happy to accept a PR from you :)

**Comment by raycohen** [comment]
at a breakpoint here: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/addon-install.js#L67
```
> givenName
'ember-cli-deploy-lightning-pack@beta'
> this.project.findAddonByName(givenName)
{ name: 'ember-cli-deploy', addons: [] }
```
seems bad.  perhaps an ember-cli issue

**Comment by raycohen** [comment]
yep.  here's the issue:

inside `findAddonByName`, it first checks for exact matches.  this fails because the value passed in includes the "@beta" suffix.

then it tries to do a prefix match.

```
  return find(this.addons, function(addon) {
    return name.indexOf(addon.name) > -1 || name.indexOf(addon.pkg.name) > -1;
  });
```
which simply matches the first addon who's name is a substring of `ember-cli-deploy-lightning-pack@beta` ... and ember-cli-deploy comes first

**Comment by lukemelia** [comment]
d'oh, good catch

**Comment by lukemelia** [comment]
Closing in favor of issue on ember-cli https://github.com/ember-cli/ember-cli/issues/2915
