### ISSUE TITLE
document rewriting index.html's asset paths in dev

### ISSUE THREAD

**Issue by raycohen** [ember-cli-deploy/ember-cli-deploy-lightning-pack#7]
To get my built development index.html file to point at my ember server, I had to

`npm install --save-dev broccoli-string-replace`

then inside `ember-cli-build.js`

```
// added to top of file
var replace = require('broccoli-string-replace');

// added before app.toTree()
  app.index = function() {
    var indexTree = EmberApp.prototype.index.call(this);

    if (this.env === 'development') { // asset-rev handles this for staging and production
      // make the js and css urls in the built development index.html
      // file point at the ember server
      var emberDevServerBaseUrl = "http://localhost:4200/";

      indexTree = replace(indexTree, {
        files: [ 'index.html' ],
        patterns: [{
          match: /href="assets\//g,
          replacement: 'href="' + emberDevServerBaseUrl + 'assets/'
        },
        {
          match: /src="assets\//g,
          replacement: 'src="' + emberDevServerBaseUrl + 'assets/'
        }]
      });
    }
    return indexTree;
  };
```

**Comment by achambers** [comment]
@raycohen What was the reason for this? Is this so that the index.html file was pointing to the correct domain where your assets are hosted? If so, you need to look at the `fingerprint` settings. See this document for details -> http://ember-cli.github.io/ember-cli-deploy/docs/v0.4.x/fingerprinting-options-and-staging-environments/

Let me know how you get on. If there is anything else you need help with, please let us know.

**Comment by lukemelia** [comment]
@achambers He's on 0.5.0-beta.2. Do these instructions still apply?

**Comment by achambers** [comment]
@lukemelia Yep, fingerprinting is defined the same way in both 0.4.x and 0.5.0

**Comment by raycohen** [comment]
fingerprint worked in dev, with the catch that I had to explicitly pass `enabled: true`

**Comment by raycohen** [comment]
On the downside, using ember-cli's built-in fingerprinting in development triggers the md5 being added to the filename.  It looks like there's no option to get the `prepend` part without the md5 part.

This is not what I want and forces me to ingest a new index.html into my server much more often than I would like.

**Comment by raycohen** [comment]
looks like there is a way to accomplish this, just not doc'd yet
https://github.com/ember-cli/ember-cli/pull/1024
