### ISSUE TITLE
tag mismatch between 0.2.0-beta.4 and 0.2.0-beta.5

### ISSUE THREAD

**Issue by bartocc** [ember-cli-deploy/ember-cli-deploy-lightning-pack#8]
Certainly not very important, but I thought it would be worth raising the point that
0.2.0-beta.5 is not tagged as beta.1 to beta.4 used to be (note the 'v' in beta.4)

deploy-lightning-pack/tree/v0.2.0-beta.4
deploy-lightning-pack/tree/0.2.0-beta.5

**Comment by achambers** [comment]
Thanks @bartocc . @lukemelia I suspect this might be due to ember-cli-release. I think you used it for the last release did you?

**Comment by lukemelia** [comment]
We're back on the right track now. Thanks!
