### ISSUE TITLE
Error during deploy (upload:redis) 'Unhandled rejection Error: ERR invalid DB index'

### ISSUE THREAD

**Issue by code0100fun** [ember-cli-deploy/ember-cli-deploy-lightning-pack#9]
The deploy seems to work. The assets get pushed to S3 and the index.html is in redis, but I can't run `ember deploy:list`.

I can do `ember deploy:activate staging --revision=beb0ae99affa04d3a785d2261d397317` which does set `<project-name>:index:current` but throws the same error.

I've tried this with heroku-redis and redistogo.

![error](http://i.imgur.com/HvdTsKe.png)

**Comment by achambers** [comment]
Hi. Can you please post the redis url you are using?

**Comment by code0100fun** [comment]
`redis://redistogo:<password>@<dbname>.redistogo.com:<port>`

**Comment by achambers** [comment]
Remove `redistogo`. There is no need for the username and the redis library doesn't like it.

**Comment by code0100fun** [comment]
Yep, that was it thanks!

**Comment by achambers** [comment]
Np

**Comment by radcliff** [comment]
**FYI: For anyone who lands here from search:**

Note that a `:` should prefix the password in the redis url, eg.

`redis://:<password>@<dbname>.redistogo.com:<port>` :eyes:
